import { Users, UsersRound, Activity, UserCheck, Mail, Phone, UserCheckIcon as UserEdit } from "lucide-react"

export const metricas = [
  {
    titulo: "Total Miembros",
    valor: "2,847",
    crecimiento: "+12.5%",
    esPositivo: true,
    icono: Users,
  },
  {
    titulo: "Grupos Activos", 
    valor: "24",
    crecimiento: "+8.3%",
    esPositivo: true,
    icono: UsersRound,
  },
  {
    titulo: "Asistencia Global",
    valor: "89.2%", 
    crecimiento: "-2.1%",
    esPositivo: false,
    icono: Activity,
  },
  {
    titulo: "Líderes Activos",
    valor: "156",
    crecimiento: "+15.7%", 
    esPositivo: true,
    icono: UserCheck,
  },
]

export const estadisticasUsuarios = [
  {
    titulo: "Total Usuarios",
    valor: "11",
    crecimiento: "+12.5%",
    esPositivo: true,
    icono: Users,
    color: "from-green-500 to-emerald-500",
  },
  {
    titulo: "Con Email",
    valor: "1", 
    crecimiento: "+8.2%",
    esPositivo: true,
    icono: Mail,
    color: "from-blue-500 to-cyan-500",
  },
  {
    titulo: "Con Teléfono",
    valor: "1",
    crecimiento: "+15.3%",
    esPositivo: true,
    icono: Phone,
    color: "from-purple-500 to-pink-500",
  },
  {
    titulo: "Editados Hoy",
    valor: "24",
    crecimiento: "+5.7%",
    esPositivo: true,
    icono: UserEdit,
    color: "from-orange-500 to-yellow-500",
  },
]

export const usuarios = [
  {
    id: 1,
    nombre: "José Giménez",
    email: "Sin email",
    telefono: "Sin teléfono",
    rol: "Pastor",
    colorRol: "bg-purple-100 text-purple-700",
    estado: "Activo",
    avatar: "JG",
  },
  {
    id: 2,
    nombre: "María Laura Navas",
    email: "Sin email",
    telefono: "Sin teléfono",
    rol: "Pastor",
    colorRol: "bg-purple-100 text-purple-700",
    estado: "Activo",
    avatar: "MN",
  },
  {
    id: 3,
    nombre: "Francisco Pacheco",
    email: "Sin email",
    telefono: "Sin teléfono",
    rol: "Director de Grupos",
    colorRol: "bg-blue-100 text-blue-700",
    estado: "Activo",
    avatar: "FP",
  },
  {
    id: 4,
    nombre: "Carlos Caballero",
    email: "Sin email",
    telefono: "Sin teléfono",
    rol: "Director de Etapa",
    colorRol: "bg-blue-100 text-blue-700",
    estado: "Activo",
    avatar: "CC",
  },
  {
    id: 5,
    nombre: "Hector Castillo",
    email: "Sin email",
    telefono: "Sin teléfono",
    rol: "Líder de Grupo",
    colorRol: "bg-teal-100 text-teal-700",
    estado: "Activo",
    avatar: "HC",
  },
  {
    id: 6,
    nombre: "Pasifae Castillo",
    email: "Sin email",
    telefono: "Sin teléfono",
    rol: "Líder de Grupo",
    colorRol: "bg-teal-100 text-teal-700",
    estado: "Activo",
    avatar: "PC",
  },
  {
    id: 7,
    nombre: "Francisco Castañeda",
    email: "Sin email",
    telefono: "Sin teléfono",
    rol: "Miembro",
    colorRol: "bg-orange-100 text-orange-700",
    estado: "Activo",
    avatar: "FC",
  },
  {
    id: 8,
    nombre: "Esther de Castañeda",
    email: "Sin email",
    telefono: "Sin teléfono",
    rol: "Miembro",
    colorRol: "bg-orange-100 text-orange-700",
    estado: "Activo",
    avatar: "EC",
  },
]